### ISSUE TITLE
set_tax_registration() broken

### ISSUE THREAD

**Issue by wcarlsen** [sentialabs/coto#6]
Cannot set tax settings from TaxRegistration Dict according to coto documentation.

Error return from put request:
Exception: failed put taxexemption/eu/vat/information: {"message":"SetTaxRegistration","type":"BPCValidationException","errorCode":"","constraintViolationCodeList":[]}

**Comment by zelentsovl** [comment]
I encountered the same issue when i tried to put state value to the string: 'authority': {'country': 'DE', 'state': 'Bayern'}. 
Changing the value to None fixed the problem: 'authority': {'country': 'DE', 'state': None}
