### ISSUE TITLE
botocore.vendored.requests removed

### ISSUE THREAD

**Issue by holgerjenczewski1007** [sentialabs/coto#8]
As stated in [this blog post](https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/), AWS now removed the vendored.requests module from botocore, rendering coto.Session dysfunctional with the new version.

Since the standard "requests" module is already in requirements.txt, fixing this should be as simple as importing this module instead of the botocore.vendored version.

**Comment by dazzle1979** [comment]
Solved in coto version 0.2.4.
